development:
  clients:
    default:
      uri: <%= ENV['DB_URL'] %>
      options:
        max_retries: 5
        retry_interval: 15
        timeout: 15
        refresh_interval: 15
        pool_size: 5

test:
  sessions:
    default:
      database: mongoid_store_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
